export const MOCK_IHP_DATA = {
    formData: {
        lastName: "Dela Cruz",
        firstName: "Juan",
        middleName: "Protacio",
        suffix: "Jr.",
        otherLegalName: "Juan P. Dela Cruz",
        placeOfBirth: "Manila, Philippines",
        nationality: "Filipino",
        usPerson: "No",
        dob: "1990-06-15",
        gender: "Male",
        civilStatus: "Married",
        countryOfResidence: "Philippines",
        durationOfStay: "34 years",
        tin: "123-456-789-000",
        presentAddress: {
            unitBuilding: "Unit 1204, Tower 1",
            lotBlockStreet: "Ayala Avenue",
            barangaySubdivision: "Bel-Air",
            cityMunicipality: "Makati City",
            province: "Metro Manila",
            country: "Philippines",
            zipCode: "1209",
        },
        workInformation: {
            address: "BGC Corporate Center, Taguig City",
            unitBuilding: "Level 25",
            lotBlockStreet: "26th Street",
            barangaySubdivision: "Fort Bonifacio",
            cityMunicipality: "Taguig City",
            province: "Metro Manila",
            country: "Philippines",
            zipCode: "1634",
            estimatedAnnualIncome: "1,200,000",
            occupation: "Software Engineer",
            employer: "Tech Solutions Inc.",
            natureOfBusiness: "Information Technology",
        },
        preferredMailingAddress: "Present",
        contactInformation: {
            primaryContact: "09171234567",
            secondaryContact: "02-8123-4567",
            email: "juan.delacruz@example.com",
        },
        sourceOfFunds: {
            business: false,
            salaryCommission: true,
            donationsContributions: false,
            remittancesAllowancesPension: false,
            investments: true,
            others: false,
        },
        contingentOwner: {
            lastName: "Dela Cruz",
            firstName: "Maria",
            middleName: "Clara",
            suffix: "",
            dob: "1992-12-25",
            relationship: "Spouse",
        },
        currentInsurance: {
            provider: "PhilHealth",
            effectiveDate: "2020-01-01",
            policyNumber: "PH-987654321",
        },
        proposedInsured: {
            sameAsApplicant: true,
            lastName: "",
            firstName: "",
            middleName: "",
            suffix: "",
            placeOfBirth: "",
            nationality: "",
            dob: "",
            gender: "",
            civilStatus: "",
            countryOfResidence: "",
            durationOfStay: "",
            tin: "",
            presentAddress: {
                unitBuilding: "",
                lotBlockStreet: "",
                barangaySubdivision: "",
                cityMunicipality: "",
                province: "",
                country: "Philippines",
                zipCode: "",
            },
            workInformation: {
                estimatedAnnualIncome: "",
                occupation: "",
                employer: "",
                natureOfBusiness: "",
            },
            relationshipToOwner: "",
            currentInsurance: { provider: "", effectiveDate: "", policyNumber: "" },
            signature: "",
            signatureDate: "",
        },
        healthDeclaration: {
            heightFeet: "5'10\"",
            heightMeters: "1.78",
            weightKg: "75",
            weightLbs: "165",
            smokeVape: false,
            smokeQuantity: "",
            alcohol: true,
            alcoholQuantity: "2-3 drinks per week",
            glassesContacts: true,
            eyeGrade: "20/20 with correction",
        },
        preExistingConditionsAcknowledged: true,
        authorizeInfoSharing: true,
        applicantSignature: "Juan Dela Cruz",
        applicantDate: new Date().toISOString().split("T")[0],
        financialAdvisor: {
            signature: "FA Signature",
            code: "FA-2024-001",
            signedDate: new Date().toISOString().split("T")[0],
        },
        authorizedRepresentative: {
            name: "",
            relationship: "",
            signature: "",
            date: "",
        },
        policyReceipt: {
            policyNo: "POL-00123456",
            signature: "",
            date: "",
            time: "",
        },
        attestation: {
            clientName: "Juan Dela Cruz",
            clientDate: new Date().toISOString().split("T")[0],
            intermediaryName: "Agent Smith",
            intermediaryDate: new Date().toISOString().split("T")[0],
        },
        remoteCommunication: {
            applicationNo: "APP-IHP-789",
            productName: "Individual Health Plan",
            date: new Date().toISOString().split("T")[0],
            mode: "Video Call",
        },
    },
    dependents: [
        {
            id: 1,
            lastName: "Dela Cruz",
            firstName: "Mateo",
            middleName: "Santos",
            suffix: "",
            otherLegalName: "",
            dob: "2015-08-10",
            gender: "Male",
            placeOfBirth: "Makati City",
            civilStatus: "Single",
            nationality: "Filipino",
            countryOfResidence: "Philippines",
            durationOfStay: "8 years",
            tin: "",
            relationship: "Son",
            presentAddress: {
                unitBuilding: "Unit 1204, Tower 1",
                lotBlockStreet: "Ayala Avenue",
                barangaySubdivision: "Bel-Air",
                cityMunicipality: "Makati City",
                province: "Metro Manila",
                country: "Philippines",
                zipCode: "1209",
            },
            workInformation: {
                unitBuilding: "",
                lotBlockStreet: "",
                barangaySubdivision: "",
                cityMunicipality: "",
                province: "",
                country: "Philippines",
                zipCode: "",
                estimatedAnnualIncome: "",
                occupation: "Student",
                employer: "",
                natureOfBusiness: "",
            },
            currentInsurance: {
                provider: "N/A",
                effectiveDate: "",
                policyNumber: "",
            },
            healthDeclaration: {
                heightFeet: "4'2\"",
                heightMeters: "1.27",
                weightKg: "30",
                weightLbs: "66",
                smokeVape: false,
                smokeQuantity: "",
                alcohol: false,
                alcoholQuantity: "",
                glassesContacts: false,
                eyeGrade: "",
            },
        },
    ],
    healthQuestions: {
        applicantOwner: {
            q1: {
                a: false,
                b: false,
                c: false,
                d: false,
                e: false,
                f: false,
                g: false,
                h: false,
                i: false,
                j: false,
                k: false,
                l: false,
                m: false,
                n: false,
                o: false,
                p: false,
            },
            q2: { a: false, b: false, c: false },
            q3: false,
            q4: false,
            q5: false,
            q6: false,
            additionalInfo: "Generally healthy.",
        },
        dependent1: {
            q1: {
                a: false,
                b: false,
                c: false,
                d: false,
                e: false,
                f: false,
                g: false,
                h: false,
                i: false,
                j: false,
                k: false,
                l: false,
                m: false,
                n: false,
                o: false,
                p: false,
            },
            q2: { a: false, b: false, c: false },
            q3: false,
            q4: false,
            q5: false,
            q6: false,
            additionalInfo: "Healthy child.",
        },
        dependent2: {
            q1: {
                a: false,
                b: false,
                c: false,
                d: false,
                e: false,
                f: false,
                g: false,
                h: false,
                i: false,
                j: false,
                k: false,
                l: false,
                m: false,
                n: false,
                o: false,
                p: false,
            },
            q2: { a: false, b: false, c: false },
            q3: false,
            q4: false,
            q5: false,
            q6: false,
            additionalInfo: "",
        },
    },
    policyInfo: {
        basePlan: "Superior Plus",
        amountInsured: "5,000,000",
        amountOfPaymentDeposit: "25,000",
        deductible: "10,000",
        coPayment: "10%",
        commencementOfCoverNote: "2024-03-01",
        areaOfCover: "Worldwide excluding USA",
        modeOfPayment: "Annual",
        paymentScheme: "Credit Card",
    },
    additionalConditions: [
        {
            questionNo: "N/A",
            nameOfPerson: "None",
            diagnosis: "N/A",
            dateOfOnset: "",
            frequencySeverity: "",
            medicalTestResults: "",
            treatment: "",
            currentStatus: "",
        },
    ],
};
